-- EXP-16：HA 集群补种数据（EXP-06 口径：P1..P10000 商品 + 库存）。
-- fresh 集群只带 P1/P2 种子，k6 8:1:1 负载查 P1..P10000 全部 miss 会引发
-- 负缓存回源风暴（见 EXP-16 报告 F1 初测）。幂等（ON DUPLICATE KEY）。
INSERT INTO products (sku, name, price_cents)
  SELECT CONCAT('P', n), CONCAT('Product ', n), 990 FROM (
    SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + 1 AS n
    FROM (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
         (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
         (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c,
         (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d
  ) seq ON DUPLICATE KEY UPDATE name = VALUES(name);

INSERT INTO inventory (sku, stock)
  SELECT CONCAT('P', n), 1000000 FROM (
    SELECT a.N + b.N*10 + c.N*100 + d.N*1000 + 1 AS n
    FROM (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
         (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
         (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c,
         (SELECT 0 AS N UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d
  ) seq ON DUPLICATE KEY UPDATE stock = VALUES(stock);

SELECT COUNT(*) AS products FROM products;
SELECT COUNT(*) AS inventory FROM inventory;
